# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js image
FROM node:slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install any needed dependencies
RUN npm install

# Bundle app source code inside the Docker image
COPY . .

# Make port 4000 available to the world outside this container
EXPOSE 4000

# Define the command to run the application
CMD ["node", "server.js"]
